name: publish

permissions:
  contents: write

on:
  push:
    branches:
    - src
    # Some tools that use GitHub Actions syntax do not support the
    # workflow_dispatch trigger. For these, you can manually simulate this
    # trigger using a push one.
    #
    # 1. Switch to the main branch of the repository.
    # 2. Ensure the branch is up-to-date.
    # 3. Create a new branch named workflow_dispatch.
    # 4. Push the branch to the remote repository.
    # 5. Wait for the action to complete.
    # 6. Delete the branch from the remote repository.
    - workflow_dispatch
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Git
      run: |
        re=$(curl --silent --header "Accept: application/json" "https://api.github.com/users/github-actions%5Bbot%5D")
        lo=$(echo "$re" | jq --raw-output ".login")
        id=$(echo "$re" | jq --raw-output ".id")
        git config --global user.name "$lo"
        git config --global user.email "$id+$lo@users.noreply.github.com"

    - name: Setup mise
      uses: jdx/mise-action@v2

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Declarations
      run: pnpm build

    - name: Publish Declarations
      working-directory: dist
      run: |
        un=$(git config --get user.name)
        ru="${{github.server_url}}/${{github.repository}}.git"
        ru=$(echo "$ru" | sed "s#https://#https://$un:${{github.token}}@#")

        td=$(mktemp -d)
        git clone --quiet --no-checkout --single-branch --branch dist "$ru" "$td"

        mv "$td/.git" .
        git add .

        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit --quiet --message "$(date --utc)"
          git push
        fi
